service: tongue-bender

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  environment:
    TELEGRAM_TOKEN: ${ssm:telegram_key}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
        - 'sqs:GetQueueUrl'
      Resource: 'arn:aws:sqs:eu-west-2:035313854880:incoming-messages'
    - Effect: 'Allow'
      Action:
        - 'sqs:ListQueues'
      Resource: 'arn:aws:sqs:eu-west-2:035313854880:incoming-messages:*'
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
        - 'sqs:GetQueueUrl'
      Resource: 'arn:aws:sqs:eu-west-2:035313854880:outgoing-messages.fifo'
    - Effect: 'Allow'
      Action:
        - 'sqs:ListQueues'
      Resource: 'arn:aws:sqs:eu-west-2:035313854880:outgoing-messages.fifo:*'
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
        - 'sqs:GetQueueUrl'
      Resource: 'arn:aws:sqs:eu-west-2:035313854880:short-delay-tasks'
    - Effect: 'Allow'
      Action:
        - 'sqs:ListQueues'
      Resource: 'arn:aws:sqs:eu-west-2:035313854880:short-delay-tasks'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:035313854880:table/users'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:035313854880:table/courses'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:035313854880:table/quizzes'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:035313854880:table/tongues'

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 3001
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: users
            sources: [./data/users.json]
          - table: courses
            sources: [./data/courses.json]
          - table: quizzes
            sources: [./data/quizzes.json]
          - table: tongues
            sources: [./data/tongues.json]

# remove _ when running offline
_resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    coursesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: courses
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    quizzesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: quizzes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    tonguesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tongues
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  hookTelegram:
    handler: handler.hookTelegram
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  sqsIncomingMessages:
    handler: handler.sqsIncomingMessages
    events:
      - sqs: arn:aws:sqs:eu-west-2:035313854880:incoming-messages

  sqsOutgoingMessages:
    handler: handler.sqsOutgoingMessages
    events:
      - sqs: arn:aws:sqs:eu-west-2:035313854880:outgoing-messages.fifo

  sqsShortDelayTasks:
    handler: handler.sqsShortDelayTasks
    events:
      - sqs: arn:aws:sqs:eu-west-2:035313854880:short-delay-tasks

  tick:
    handler: handler.tick
    events:
      - schedule: rate(10 minutes)
